### ISSUE TITLE
Fix url links.

### ISSUE THREAD

**Issue by evgip** [lightvue/light-icons#6]
On the page: https://icons.lightvue.org/icons
In the basement there is an inscription: Licensed under MIT. (Yes it's free and _open-sourced_)

The link leads to a page that does not exist: https://github.com/plug-ui/light-icons

**Comment by bharat-dussa** [comment]
I guess URL Should be Like this.
**https://github.com/lightvue/light-icons**

**Comment by BashCloud** [comment]
Thanks @evgip & @bharat-dussa for your valuable contributions. ✌️
